### ISSUE TITLE
Crashes forever on D1 mini, Initializing SPIFFS...Failed!

### ISSUE THREAD

**Issue by skickar** [ridercz/HoneyESP#2]
I get this, forever, when uploading to a D1 mini.

 
|_| | |___ ___) |  __/  github.com/ridercz/HoneyESP
|_| |_|\___/|_| |_|\___|\__, |_____|____/|_|     (c) 2018-2019 Michal Altair Valasek
                        |___/                    www.altairis.cz | www.rider.cz

Initializing SPIFFS...Failed!
System halted.

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffd80 end: 3fffffc0 offset: 01b0
3fffff30:  feefeffe feefeffe feefeffe feefeffe  
3fffff40:  feefeffe feefeffe feefeffe feefeffe  
3fffff50:  feefeffe feefeffe feefeffe feefeffe  
3fffff60:  feefeffe feefeffe feefeffe feefeffe  
3fffff70:  feefeffe feefeffe feefeffe feefeffe  
3fffff80:  feefeffe feefeffe feefeffe feefeffe  
3fffff90:  feefeffe feefeffe feefeffe 3ffee9a4  
3fffffa0:  3fffdad0 00000000 3ffee974 40207b48  
3fffffb0:  feefeffe feefeffe 3ffe850c 40100479  
<<<stack<<<
?(⸮⸮L⸮⸮DH"⸮
 _   _                        _____ ____  ____
| | | | ___  _ __   ___ _   _| ____/ ___||  _ \  ESP8266/ESP32 honeypot version 2.0
| |_| |/ _ \| '_ \ / _ \ | | |  _| \___ \| |_) | SPIFFS Version
|  _  | (_) | | | |  __/ |_| | |___ ___) |  __/  github.com/ridercz/HoneyESP
|_| |_|\___/|_| |_|\___|\__, |_____|____/|_|     (c) 2018-2019 Michal Altair Valasek
                        |___/                    www.altairis.cz | www.rider.cz

Initializing SPIFFS...Failed!
System halted.

**Comment by ridercz** [comment]
If SPIFFS initialization fails, you have most likely wrong board parameters selected. Other guess is a bad board.
